service: serverless-akurey-source
frameworkVersion: '3'
provider:
  name: aws
  runtime: nodejs14.x
  timeout: 30 # maximum of 30 second for api gateway
  environment:
    SLACK_SIGNING_SECRET: ${env:SLACK_SIGNING_SECRET}
    SLACK_BOT_TOKEN: ${env:SLACK_BOT_TOKEN}
    GITHUB_TOKEN: ${env:GITHUB_TOKEN}
functions:
  slack:
    handler: app.handler
    events:
      - http:
          path: slack/events
          method: post
  githubUtils:
    handler: utils/githubUtils.handler
plugins:
  - serverless-offline